UMLRazor/Pages/Customers/DeleteCustomer.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLibrary.Interfaces;
using PizzaLibrary.Models;

namespace UMLRazor.Pages.Customers
{
    public class DeleteCustomerModel : PageModel
    {
        private ICustomerRepository _repo;
        
        [BindProperty]
        public Customer Customer { get; set; }

        public DeleteCustomerModel(ICustomerRepository customerRepository)
        {
            this._repo = customerRepository;
        }

        public IActionResult OnGet(string deleteMobile)
        {
            Customer = _repo.GetCustomerByMobile(deleteMobile);
            return Page();
        }
        //public void OnGet(int deleteId)
        //{
        //    Customer = _repo.GetCustomerById(deleteId);
        //}

        public IActionResult OnPost()
        {
            _repo.RemoveCustomer(Customer.Mobile);
            return RedirectToPage("ShowCustomers");
        }
    }
}

UMLRazor/Pages/Customers/ShowCustomers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLibrary.Interfaces;
using PizzaLibrary.Services;
using PizzaLibrary.Models;

namespace UMLRazor.Pages.Customers
{
    public class ShowCustomersModel : PageModel
    {
        private ICustomerRepository _customerRepo;
       
        public List<Customer> Customers { get; private set; }
        
        public ShowCustomersModel(ICustomerRepository customerRepository)
        {
            _customerRepo = customerRepository;
        }
        public void OnGet()
        {
            Customers = _customerRepo.GetAll();
        }
    }
}

UMLRazor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace UMLRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

UMLRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UMLRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public string Message { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            Message = "Today's offer is a super meal...";
        }
    }
}

UMLRazor/Pages/MenuItems/DeleteMenuItem.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLibrary.Interfaces;
using PizzaLibrary.Models;

namespace UMLRazor.Pages.MenuItems
{
    public class DeleteMenuItemModel : PageModel
    {
        private IMenuItemRepository _repo;

        [BindProperty]
        public MenuItem MenuItem { get; set; }

        public DeleteMenuItemModel(IMenuItemRepository menuItemRepository)
        {
            this._repo = menuItemRepository;
        }

        public void OnGet(int deleteNo)
        {
            MenuItem = _repo.GetMenuItemByNo(deleteNo);
        }

        public IActionResult OnPost(int deleteNo)
        {
            _repo.RemoveMenuItem(deleteNo);
            return RedirectToPage("ShowMenuItems");
        }
    }
}

UMLRazor/Pages/MenuItems/ShowMenuItems.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLibrary.Interfaces;
using PizzaLibrary.Models;

namespace UMLRazor.Pages.MenuItems
{
    public class ShowMenuItemsModel : PageModel
    {
        private IMenuItemRepository _menuItemRepo;

        public List<MenuItem> MenuItems { get; private set; }

        public ShowMenuItemsModel(IMenuItemRepository menuItemRepository)
        {
            _menuItemRepo = menuItemRepository;
        }
        public void OnGet()
        {
            MenuItems = _menuItemRepo.GetAll();
        }
    }
}

UMLRazor/Pages/Orders/CreateOrder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PizzaLibrary.Interfaces;
using PizzaLibrary.Models;
using PizzaLibrary.Services;

namespace UMLRazor.Pages.Orders
{
    public class CreateOrderModel : PageModel
    {
        private ICustomerRepository _cRepo;
        private IMenuItemRepository _mRepo;
        private IShoppingBasket _shoppingBasket;

        #region Properties
        public string MessageCustomer { get; set; }
        public string MessageOrder { get; set; }
        [BindProperty]
        public bool Delivery { get; set; }
        [BindProperty]
        public string SearchCustomerMobile { get; set; }
        public Customer TheCustomer { get; set; }
        [BindProperty]
        public int ChosenMenuItem { get; set; }
        public List<SelectListItem> MenuItemSelectList { get; set; }
        [BindProperty]
        public int Amount { get; set; }
        [BindProperty]
        public string Comment { get; set; }
        public List<OrderLine> OrderLines { get; set; }
        #endregion

        #region Constructor
        public CreateOrderModel(ICustomerRepository customerRepository,
                                IMenuItemRepository menuItemRepository,
                                IShoppingBasket shoppingBasket)
        {
            _cRepo = customerRepository;
            _mRepo = menuItemRepository;
            _shoppingBasket = shoppingBasket;
            OrderLines = _shoppingBasket.GetAll();
            TheCustomer = _shoppingBasket.Customer;
            createMenuSelectList();
        }
        #endregion

        #region Methods
        private void createMenuSelectList() // small first letter for private methods
        {
            MenuItemSelectList = new List<SelectListItem>();
            MenuItemSelectList.Add(new SelectListItem("Select an item", "-1"));
            foreach (MenuItem item in _mRepo.GetAll())
            {
                SelectListItem sli = new SelectListItem(item.Name, item.No.ToString());
                MenuItemSelectList.Add(sli);
            }
        }

        public void OnGet()
        {
        }

        public void OnPostCustomer()
        {
            TheCustomer = _cRepo.GetCustomerByMobile(SearchCustomerMobile);
            _shoppingBasket.Customer = TheCustomer;
            if (TheCustomer == null)
            {
                MessageCustomer = "404: Customer not found";
            }
        }

        public void OnPostAddToOrder()
        {
            if (Amount > 0)
            {
                MenuItem menuItemToOrder = _mRepo.GetMenuItemByNo(ChosenMenuItem);
                if (menuItemToOrder != null)
                {
                    OrderLine ol = new OrderLine(Amount, menuItemToOrder, Comment);
                    _shoppingBasket.AddOrderLine(ol);
                }
            }
        }

        public IActionResult OnPostDelete(int deleteId)
        {
            _shoppingBasket.DeleteOrderLine(deleteId);
            return Page();
        }

        public IActionResult OnPostCreateOrder()
        {
            if (_shoppingBasket.Customer == null || _shoppingBasket.Count == 0)
            {
                MessageOrder = "Error: Customer is not selected or there is no item in your cart";
                return Page();
            }
            return RedirectToPage("ShowOrder");
            //should save and print customer info, orderlines, total price (reciept) over to ShowOrder
        }
        #endregion
    }
}

UMLRazor/Pages/Orders/ShowOrder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLibrary.Interfaces;
using PizzaLibrary.Models;

namespace UMLRazor.Pages.Orders
{
    public class ShowOrderModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

UMLRazor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UMLRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

UMLRazor/Pages/Customers/AddCustomer.cshtml
@page
@model UMLRazor.Pages.Customers.AddCustomerModel
@{
    ViewData["Title"] = "Add Customer";
}

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="@Model.Customer.Name" class="control-label"></label>
        <input asp-for="@Model.Customer.Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Customer.Mobile" class="control-label"></label>
        <input asp-for="@Model.Customer.Mobile" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Customer.Address" class="control-label"></label>
        <input asp-for="@Model.Customer.Address" class="form-control" />
    </div>
    @* <div class="form-group">
        <label asp-for="@Model.Photo" class="control-label"></label>
        <div></div>
    </div> *@
    <div class="formgroup">
        <label asp-for="@Model.Customer.Name" class="control-label"></label>
        <input type="submit" value="Create Customer" class="btn btn-primary" />
    </div>
</form>

UMLRazor/Pages/Customers/DeleteCustomer.cshtml
@page
@model UMLRazor.Pages.Customers.DeleteCustomerModel
@{
    ViewData["Title"] = "Delete Customer";
}
<h1>Delete Customer</h1>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Customer.Id" class="control-label"></label>
                <input asp-for="@Model.Customer.Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Customer.Name" class="control-label"></label>
                <input asp-for="@Model.Customer.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Customer.Address" class="control-label"></label>
                <input asp-for="@Model.Customer.Address" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Customer.Mobile" class="control-label"></label>
                <input asp-for="@Model.Customer.Mobile" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Customer.ClubMember" class="control-label"></label>
                @* <input asp-for="@Model.Customer.ClubMember" class="form-control"></input> *@
                <input value="@(Model.Customer.ClubMember?"Er medlem":"Ikke medlem")" class="form-control"></input>
            </div>
            <div class="formgroup">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div>
        <a asp-page="ShowCustomers">Back to List</a>
    </div>
</div>

UMLRazor/Pages/Customers/EditCustomer.cshtml
@page
@model UMLRazor.Pages.Customers.EditCustomerModel
@{
    ViewData["Title"] = "Edit Customer";
}
<h1>Edit Customer</h1>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Name" class="control-label"></label>
                <input asp-for="@Model.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.Address" class="control-label"></label>
                <input asp-for="@Model.Address" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.newMobile" class="control-label"></label>
                <input asp-for="@Model.newMobile" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.ClubMember" class="control-label"></label>
                <input type="checkbox" name="ChooseClub" value="true"></input>
            </div>
            <div class="formgroup">
                <input type="submit" value="Edit Customer" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div>
        <a asp-page="ShowCustomers">Back to List</a>
    </div>
</div>

UMLRazor/Pages/Customers/ShowCustomers.cshtml
@page
@using PizzaLibrary.Models;
@model UMLRazor.Pages.Customers.ShowCustomersModel
@{
    ViewData["Title"] = "ShowCustomers";
}

<h1>Number of Customers @Model.Customers.Count</h1>

<p>
    <a asp-page="AddCustomer">Add New Customer</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Address</th>
            <th>Mobile</th>
            <th>ClubMember</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Customer item in Model.Customers)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Address</td>
                <td>@item.Mobile</td>
                <td>@item.ClubMember</td>
                <td><a asp-page="EditCustomer" asp-route-editMobile="@item.Mobile">Edit</a></td>
                <td><a asp-page="DeleteCustomer" asp-route-deleteMobile="@item.Mobile">Delete</a></td>
                @* <td><a asp-page="DeleteCustomer" asp-route-deleteId="@item.Id">Delete</a></td> *@
            </tr>
        }
    </tbody>
</table>

UMLRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Big Mamma Index";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>Welcome to Big Mamma Pizzaria date: @DateTime.Now.ToShortDateString()</p>
    @for(int i = 0; i<4; i++)
    {
        <p>@Model.Message</p>
    }
</div>

UMLRazor/Pages/MenuItems/AddMenuItem.cshtml
@page
@model UMLRazor.Pages.MenuItems.AddMenuItemModel
@{
    ViewData["Title"] = "Add Menu Item";
}

<form method="post">
    <div class="form-group">
        <label asp-for="@Model.MenuItem.Name" class="control-label"></label>
        <input asp-for="@Model.MenuItem.Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.MenuItem.Price" class="control-label"></label>
        <input asp-for="@Model.MenuItem.Price" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="@Model.MenuItem.Description" class="control-label"></label>
        <input asp-for="@Model.MenuItem.Description" class="form-control" />
    </div>
    <div class="form-group">
        <label>Select Menu Type </label>
        <select id="ChosenMenuType" name="ChosenMenuType"
                asp-for="@Model.ChosenMenuType" asp-items="@Model.MenuTypeSelectList">
        </select>
    </div>
    <div class="formgroup">
        <label asp-for="@Model.MenuItem.Name" class="control-label"></label>
        <input type="submit" value="Create Menu Item" class="btn btn-primary" />
    </div>
</form>

UMLRazor/Pages/MenuItems/DeleteMenuItem.cshtml
@page
@model UMLRazor.Pages.MenuItems.DeleteMenuItemModel
@{
    ViewData["Title"] = "Delete Menu Item";
}
<h1>Delete Menu Item</h1>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.MenuItem.No" class="control-label"></label>
                <input asp-for="@Model.MenuItem.No" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MenuItem.Name" class="control-label"></label>
                <input asp-for="@Model.MenuItem.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MenuItem.Price" class="control-label"></label>
                <input asp-for="@Model.MenuItem.Price" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MenuItem.Description" class="control-label"></label>
                <input asp-for="@Model.MenuItem.Description" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="@Model.MenuItem.TheMenuType" class="control-label"></label>
                <input asp-for="@Model.MenuItem.TheMenuType" class="form-control" />
            </div>
            <div class="formgroup">
                <input type="submit" value="Delete" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div>
        <a asp-page="ShowMenuItems">Back to List</a>
    </div>
</div>

UMLRazor/Pages/MenuItems/ShowMenuItems.cshtml
@page
@using PizzaLibrary.Interfaces;
@using PizzaLibrary.Models;
@using PizzaLibrary.Services;
@model UMLRazor.Pages.MenuItems.ShowMenuItemsModel
@{
    ViewData["Title"] = "ShowMenuItems";
}

<h1>Number of Menu Items @Model.MenuItems.Count</h1>

<p>
    <a asp-page="AddMenuItem">Add New Menu Item</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>TheMenuType</th>
        </tr>
    </thead>
    <tbody>
        @foreach (MenuItem item in Model.MenuItems)
        {
            <tr>
                <td>@item.No</td>
                <td>@item.Name</td>
                <td>@item.Price</td>
                <td>@item.Description</td>
                <td>@item.TheMenuType</td>
                <td><a asp-page="EditMenuItem" asp-route-name="@item.Name">Edit</a></td>
                <td><a asp-page="DeleteMenuItem" asp-route-deleteNo="@item.No">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

UMLRazor/Pages/Orders/CreateOrder.cshtml
@page
@model UMLRazor.Pages.Orders.CreateOrderModel
@{
    ViewData["Title"] = "Create Order";
}

<h3>Select Customer</h3>
<form method="post" asp-page-handler="Customer"><p>
    Mobile : <input type="text>" asp-for="SearchCustomerMobile" />
    <input type="submit" value="Search customer" />
</p></form>

<h3><span class="text-danger">@Model.MessageCustomer</span></h3>

@{
    if (@Model.TheCustomer != null)
    {
        <p>
        Navn: @Model.TheCustomer.Name
        <br />
        Adresse: @Model.TheCustomer.Address
        <br />
        Mobil: @Model.TheCustomer.Mobile
        </p>
        
    }
}

<h3>Add to Order</h3>
<form method="post" asp-page-handler="AddToOrder">
    <label>MenuItems</label>
    <select id="ChosenMenuItem" name="ChosenMenuItem"
    asp-for="@Model.ChosenMenuItem" asp-items="@Model.MenuItemSelectList">
    </select>

    <input type="number" asp-for="@Model.Amount" />
    <textarea asp-for="@Model.Comment" cols="120">
    </textarea>
    <input type="submit" value="AddToOrder" />
</form>

<h3>Shopping Basket</h3>
@{
    if (Model.OrderLines != null && Model.OrderLines.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Amount</th>
                    <th>Product</th>
                    <th>Subtotal</th>
                    <th>Comment</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrderLines)
                {
                    <tr>
                        <td>@item.Amount</td>
                        <td>@item.MenuItem.Name</td>
                        <td>@item.SubTotal()</td>
                        <td>@item.Comment</td>
                        <td>
                            <form method="post" asp-page-handler="Delete" asp-route-deleteId="@item.Id">
                                <input type="submit" value="Delete" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

<form method="radio">
    <input type="radio" asp-for="Delivery" value="True"/> Delivery
    <br />
    <input type="radio" asp-for="Delivery" value="False"/> Eat here
</form>

<h3><span class="text-danger">@Model.MessageOrder</span></h3>

<form method="post" asp-page-handler="CreateOrder">
    <p>
        <input type="submit" value="Create Order" />
    </p>
</form>

UMLRazor/Pages/Orders/ShowOrder.cshtml
@page
@model UMLRazor.Pages.Orders.ShowOrderModel
@{
    ViewData["Title"] = "Show Order";
}

<h3>Order Reciept</h3>
@* Show CompanyInfo singleton info here (remember to implement singleton in Program) *@

<h3>Ordered Items</h3>
<table class="table">
    <thead>
        <tr>
            <th>Amount</th>
            <th>Product</th>
            <th>Subtotal</th>
            <th>Comment</th>
        </tr>
    </thead>
    <tbody>
        @* @foreach (var item in Model.OrderLines)
        {
            <tr>
                <td>@item.Amount</td>
                <td>@item.MenuItem.Name</td>
                <td>@item.SubTotal()</td>
                <td>@item.Comment</td>
            </tr>
        } *@
    </tbody>
</table>

UMLRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UMLRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UMLRazor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">UMLRazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Customers/ShowCustomers">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Customers/AddCustomer">Create Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/MenuItems/ShowMenuItems">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Orders/CreateOrder">Create Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - UMLRazor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>